name: Build and Deploy Flask App to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Cache pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Show Python executable and environment before install
      run: |
        which python
        python --version
        echo "PYTHONPATH: $PYTHONPATH"
        echo "VIRTUAL_ENV: $VIRTUAL_ENV"
        python -m site

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .

    - name: Show Python executable and environment after install
      run: |
        which python
        python --version
        echo "PYTHONPATH: $PYTHONPATH"
        echo "VIRTUAL_ENV: $VIRTUAL_ENV"
        python -m site
        pip list

    - name: Show Gunicorn version and command
      run: |
        pip show gunicorn || echo "Gunicorn not installed"
        which gunicorn || echo "Gunicorn not found in PATH"
        echo "About to run: gunicorn main:app"
        env | grep -i python || true

    - name: Run tests
      run: |
        pip install pytest
        pytest

    - name: Install Bicep CLI
      run: |
        az bicep install

    - name: Azure Login
      if: success()
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure Web App'
      if: success()
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'jcflask'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: .
        startup-command: 'gunicorn main:app'

    - name: Verify Azure Web App deployment logs
      if: success()
      run: |
        echo "Check Azure Web App logs via Azure Portal or 'az webapp log tail --name jcflask --resource-group <your-resource-group>' to verify requirements are installed."
